import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <header className="bg-pink-200 p-10 flex gap-5">
          <Link href='/'>Home</Link>
          <Link href='/PressThis'>Press This</Link>
          <Link href='/PressThis/Message'>Message</Link>
          <Link href='/nested1'>Nested</Link>
        </header>
        {children}
        <footer className="bg-slate-400 p-5 w-50">Bye</footer>
        </body>
    </html>
  );
}
 